apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dagster-cluster-role
  labels:
    app: dagster
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  - jobs/status
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/status
  - events
  verbs:
  - '*'