# cm-workspace.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-workspace
  namespace: dagster
data:
  workspace.yaml: |
    load_from:
      - grpc_server:
          location_name: "medallion-air"
          host: "medallion-air"
          port: 4266
      - grpc_server:
          location_name: "medallion-weather"
          host: "medallion-weather"
          port: 4266
