####################################################################################################
# User Code Deployments: Configuration for user code containers to be loaded via GRPC server. For
# each item in the "deployments" list, a K8s Deployment and K8s Service will be created to run the
# GRPC server that Dagit/Dagster communicates with to get repository information and the current
# image information. These deployments can be updated independently of Dagit, and Dagit/Dagster
# will pull the current image for all execution. When using a distributed executor (such as
# Celery-K8s) for pipeline run, the current image will be queried once and used for all
# solid executions for that pipeline run. In order to guarantee that all solid executions within a
# pipeline execution use the same image, we recommend using a unique tag (ie not "latest").
#
# All user code will be invoked within the images.
####################################################################################################
deployments:
  - name: "medallion-weather"
    image:
      repository: "georgelai/medallion-weather"
      tag: "0.1.0"
      pullPolicy: "IfNotPresent"
    dagsterApiGrpcArgs:
      - "-m"
      - "medallion_weather"
    port: 4266
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"
    volumes:
      - name: "gcp-creds-vol"
        secret:
          secretName: "medallion-weather-gcp-creds"
          items:
            - key: "adc"
              path: "application_default_credentials.json"
          defaultMode: 0444
    volumeMounts:
      - name: "gcp-creds-vol"
        mountPath: "/root"
    env:
      MEDALLION_WEATHER_ENV: dev
      MEDALLION_WEATHER_WEATHER_URI: https://opendata.cwb.gov.tw/api/v1/rest/datastore/O-A0001-001?Authorization=rdec-key-123-45678-011121314
      MEDALLION_WEATHER_RAIN_URI: https://opendata.cwb.gov.tw/api/v1/rest/datastore/O-A0002-001?Authorization=rdec-key-123-45678-011121314

    envSecrets:
      - name: "medallion-weather-secret-envs"
  - name: "medallion-air"
    image:
      repository: "georgelai/medallion-air"
      tag: "0.1.0"
      pullPolicy: "IfNotPresent"
    dagsterApiGrpcArgs:
      - "-m"
      - "medallion_air"
    port: 4266
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"
    volumes:
      - name: "gcp-creds-vol"
        secret:
          secretName: "medallion-air-gcp-creds"
          items:
            - key: "adc"
              path: "application_default_credentials.json"
          defaultMode: 0444
    volumeMounts:
      - name: "gcp-creds-vol"
        mountPath: "/root"
    env:
      MEDALLION_AIR_ENV: dev
      MEDALLION_AIR_PM25_URI: https://data.epa.gov.tw/api/v2/aqx_p_02?api_key=e8dd42e6-9b8b-43f8-991e-b3dee723a52d&limit=1000&sort=ImportDate%20desc&format=json
      MEDALLION_AIR_PM10_URI: https://data.epa.gov.tw/api/v2/aqx_p_319?api_key=e8dd42e6-9b8b-43f8-991e-b3dee723a52d&limit=1000&sort=ImportDate%20desc&format=json
      MEDALLION_AIR_AQI_URI: https://data.epa.gov.tw/api/v2/aqx_p_432?api_key=e8dd42e6-9b8b-43f8-991e-b3dee723a52d&limit=1000&sort=ImportDate%20desc&format=json

    envSecrets:
      - name: "medallion-air-secret-envs"
