deployments:
  - name: "medallion-weather"
    image:
      repository: "georgelai/medallion_weather"
      tag: "0.1.3"
      pullPolicy: "IfNotPresent"
    dagsterApiGrpcArgs:
      - "-m"
      - "medallion_weather"
    port: 4266
    resources:
      requests:
        cpu: "250m"
        memory: "500Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"
    volumes:
      - name: "gcp-creds-vol"
        secret:
          secretName: "medallion-weather-gcp-creds"
          items:
            - key: "adc"
              path: "application_default_credentials.json"
          defaultMode: 0444
    volumeMounts:
      - name: "gcp-creds-vol"
        mountPath: "/root"
    env:
      MEDALLION_WEATHER_ENV: dev
      MEDALLION_WEATHER_WEATHER_URI: https://opendata.cwa.gov.tw/api/v1/rest/datastore/O-A0001-001?Authorization=rdec-key-123-45678-011121314
      MEDALLION_WEATHER_RAIN_URI: https://opendata.cwa.gov.tw/api/v1/rest/datastore/O-A0002-001?Authorization=rdec-key-123-45678-011121314

    envSecrets:
      - name: "medallion-weather-secret-envs"
extraManifests:
  - apiVersion: v1
    data:
      postgresql-password: ZGFnc3Rlcg==
    kind: Secret
    metadata:
      labels:
        app: dagster
      name: dagster-postgresql-secret
    type: Opaque