#!/bin/bash

MEDALLION_AIR_VERSION=0.1.2
MEDALLION_WEATHER_VERSION=0.1.2
DAGSTER_CHART_VERSION=1.2.1
DASK_CHART_VERSION=2023.1.0

kind delete clusters --all

helm repo update

kind create cluster --name=dev

kind load docker-image --name=dev georgelai/medallion-air:${MEDALLION_AIR_VERSION}
kind load docker-image --name=dev georgelai/medallion-weather:${MEDALLION_WEATHER_VERSION}

kubectl create ns dagster
kubectl --namespace=dagster apply -f cm-dagster-workspace.yaml
kubectl --namespace=dagster create secret generic medallion-air-secret-envs \
	--from-literal=GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT} \
	--from-literal=GOOGLE_APPLICATION_CREDENTIALS=/root/application_default_credentials.json
kubectl --namespace=dagster create secret generic medallion-air-gcp-creds \
	--from-file=adc=${GOOGLE_APPLICATION_CREDENTIALS}
kubectl --namespace=dagster create secret generic medallion-weather-secret-envs \
	--from-literal=GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT} \
	--from-literal=GOOGLE_APPLICATION_CREDENTIALS=/root/application_default_credentials.json
kubectl --namespace=dagster create secret generic medallion-weather-gcp-creds \
	--from-file=adc=${GOOGLE_APPLICATION_CREDENTIALS}

#helm --namespace=dagster upgrade \
#  dask \
#  dask/dask \
#  --install \
#  --version=${DASK_CHART_VERSION} \
#  --values=dask-values.yaml

helm --namespace=dagster upgrade \
  dagster \
  dagster/dagster \
  --install \
  --version=${CHART_VERSION} \
  --values=dagster-values.yaml

helm --namespace=dagster upgrade \
  dagster-user-deployments \
  dagster/dagster-user-deployments \
  --install \
  --version=${CHART_VERSION} \
  --values=dagster-user-deployments-values.yaml
